[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x', 'ffmpeg', 'pkg-config', 'fontconfig', 'dejavu_fonts']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start' 